name: labeler

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labeler.yml'
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Run labeler
        uses: boywithkeyboard/labeler@main
