name: labeler

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labeler.yml'
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Run labeler
        uses: boywithkeyboard/labeler@main
