name: labeler

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labeler.yml'
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Run labeler
        uses: boywithkeyboard/labeler@main
